# Specifications for validate_drp metrics against validation_data_decam

---
# Select the DECAM test dataset
id: 'base'
metadata_query:
  instrument: 'DECAM'
  dataset_repo_url: 'https://github.com/lsst/validation_data_decam.git'
  # May need to add specific visits and ccds for the test dataset

---
id: 'base-u'
base: '#base'
metadata_query:
  filter_name: 'u'

---
id: 'base-z'
base: '#base'
metadata_query:
  filter_name: 'z'

---
id: 'base-y'
base: '#base'
metadata_query:
  filter_name: 'y'

---
name: 'FY17_decam_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY18_decam_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY19_decam_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY20_decam_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'ORR_decam_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY17_decam_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY18_decam_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY19_decam_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY20_decam_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'ORR_decam_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY17_decam_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY18_decam_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY19_decam_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY20_decam_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'ORR_decam_y'
base: ['PA1.FY17_uzy', '#base-y']
