# Specifications for validate_drp metrics against validation_data_hsc
# uzy-band datasets.

---
# Select the HSC test dataset
id: 'hsc'
metadata_query:
  instrument: 'HSC'
  dataset_repo_url: 'https://github.com/lsst/validation_data_hsc.git'
  dataset_name: validation_data_hsc
  # may need to add some visits

---
id: 'hsc-u'
base: '#hsc'
metadata_query:
  filter_name: 'HSC-U'

---
id: 'hsc-z'
base: '#hsc'
metadata_query:
  filter_name: 'HSC-Z'

---
id: 'hsc-y'
base: '#hsc'
metadata_query:
  filter_name: 'HSC-Y'
