# Specifications for validate_drp metrics against validation_data_hsc
# uy-band datasets. 

---
# Select the HSC test dataset
id: 'base'
metadata_query:
  dataset_repo_url: 'https://github.com/lsst/validation_data_hsc.git'
  # may need to add some visits

---
id: 'base-u'
base: '#base'
metadata_query:
  filter_name: 'HSC-U'

---
id: 'base-y'
base: '#base'
metadata_query:
  filter_name: 'HSC-Y'
