# Specifications for validate_drp metrics against validation_data_hsc

---
# Select the HSC test dataset
id: 'hsc'
metadata_query:
  instrument: 'HSC'
  dataset_repo_url: 'https://github.com/lsst/validation_data_hsc.git'
  dataset_name: 'validation_data_hsc'
  # May need to add specific visits and ccds for the test dataset

---
id: 'hsc-g'
base: '#hsc'
metadata_query:
  filter_name: 'HSC-G'

---
id: 'hsc-r'
base: '#hsc'
metadata_query:
  filter_name: 'HSC-R'

---
id: 'hsc-i'
base: '#hsc'
metadata_query:
  filter_name: 'HSC-I'
