# Specifications for validate_drp metrics against validation_data_cfht

---
# Select the CFHT test dataset
id: 'base'
metadata_query:
  instrument: 'CFHT'
  dataset_repo_url: 'https://github.com/lsst/validation_data_cfht.git'
  # May need to add specific visits and ccds for the test dataset

---
id: 'base-u'
base: '#base'
metadata_query:
  filter_name: 'u'

---
id: 'base-z'
base: '#base'
metadata_query:
  filter_name: 'z'

---
id: 'base-y'
base: '#base'
metadata_query:
  filter_name: 'y'

---
name: 'FY17_cfht_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY18_cfht_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY19_cfht_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY20_cfht_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'ORR_cfht_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY17_cfht_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY18_cfht_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY19_cfht_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY20_cfht_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'ORR_cfht_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY17_cfht_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY18_cfht_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY19_cfht_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY20_cfht_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'ORR_cfht_y'
base: ['PA1.FY17_uzy', '#base-y']
