# Specifications for validate_drp metrics against validation_data_cfht
# gri-band datasets. The `base` partial provides a metadata query that
# makes these specifications only test measurements made from the example
# CFHT MegaCam visit 849375, 850587 dataset in g, r, and i bands. This same
# dataset in used by validate_drp Jenkins jobs.

---
# Select the CFHT test dataset
id: 'cfht'
metadata_query:
  instrument: 'CFHT'
  dataset_repo_url: 'https://github.com/lsst/validation_data_cfht.git'
  dataset_name: 'validation_data_cfht'
  visits: [849375, 850587]
  ccds: [12, 13, 14, 21, 22, 23]

---
id: 'cfht-u'
base: '#cfht'
metadata_query:
  filter_name: 'u'

---
id: 'cfht-z'
base: '#cfht'
metadata_query:
  filter_name: 'z'

---
id: 'cfht-y'
base: '#cfht'
metadata_query:
  filter_name: 'y'
