# Specifications for validate_drp metrics against validation_data_decam
# gri-band datasets. The `base` partial provides a metadata query that
# makes these specifications only test measurements made on DECam data
# in the g, r, or i bands.

---
# Select the CFHT test dataset
id: 'base'
metadata_query:
  instrument: 'DECAM'
  dataset_repo_url: 'https://github.com/lsst/validation_data_decam.git'

---
id: 'base-g'
base: '#base'
metadata_query:
  filter_name: 'g'

---
id: 'base-r'
base: '#base'
metadata_query:
  filter_name: 'r'

---
id: 'base-i'
base: '#base'
metadata_query:
  filter_name: 'i'
