# Specifications for validate_drp metrics against validation_data_decam
# gri-band datasets. The `base` partial provides a metadata query that
# makes these specifications only test measurements made on DECam data
# in the u, z, or y bands.

---
# Select the CFHT test dataset
id: 'base'
metadata_query:
  instrument: 'DECAM'
  dataset_repo_url: 'https://github.com/lsst/validation_data_decam.git'

---
id: 'base-u'
base: '#base'
metadata_query:
  filter_name: 'u'

---
id: 'base-z'
base: '#base'
metadata_query:
  filter_name: 'z'

---
id: 'base-y'
base: '#base'
metadata_query:
  filter_name: 'y'
