# Specifications for validate_drp metrics against validation_data_decam
# gri-band datasets. The `base` partial provides a metadata query that
# makes these specifications only test measurements made on DECam data
# in the u, z, or y bands.

---
# Select the CFHT test dataset
id: 'decam'
metadata_query:
  instrument: 'DECAM'
  dataset_repo_url: 'https://github.com/lsst/validation_data_decam.git'
  dataset_name: 'validation_data_decam'
  # May need to add specific visits and ccds for the test dataset

---
id: 'decam-u'
base: '#decam'
metadata_query:
  filter_name: 'u'

---
id: 'decam-z'
base: '#decam'
metadata_query:
  filter_name: 'z'

---
id: 'decam-y'
base: '#decam'
metadata_query:
  filter_name: 'y'
