---
name: 'hsc'
base: 'AD1_design.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD1_minimum.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD1_stretch.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD2_design.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD2_minimum.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD2_stretch.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD3_design.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD3_minimum.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AD3_stretch.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF1_design.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF1_minimum.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF1_stretch.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF2_design.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF2_minimum.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF2_stretch.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF3_design.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF3_minimum.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc'
base: 'AF3_stretch.srd'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_design'
base: 'AM1.design'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_minimum'
base: 'AM1.minimum'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_stretch'
base: 'AM1.stretch'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_design'
base: 'AM2.design'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_minimum'
base: 'AM2.minimum'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_stretch'
base: 'AM2.stretch'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_design'
base: 'AM3.design'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_minimum'
base: 'AM3.minimum'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_stretch'
base: 'AM3.stretch'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_design'
base: 'TE1.design'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_minimum'
base: 'TE1.minimum'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_stretch'
base: 'TE1.stretch'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_design'
base: 'TE2.design'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_minimum'
base: 'TE2.minimum'
metadata_query:
  instrument: 'HSC'

---
name: 'hsc_stretch'
base: 'TE2.stretch'
metadata_query:
  instrument: 'HSC'