# Specifications for validate_drp metrics against validation_data_hsc

---
# Select the HSC test dataset
id: 'base'
metadata_query:
  instrument: 'HSC'
  dataset_repo_url: 'https://github.com/lsst/validation_data_hsc.git'
  # May need to add specific visits and ccds for the test dataset

---
id: 'base-u'
base: '#base'
metadata_query:
  filter_name: 'HSC-U'

---
id: 'base-z'
base: '#base'
metadata_query:
  filter_name: 'HSC-Z'

---
id: 'base-y'
base: '#base'
metadata_query:
  filter_name: 'HSC-Y'

---
name: 'FY17_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY18_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY19_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY20_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'ORR_u'
base: ['PA1.FY17_uzy', '#base-u']

---
name: 'FY17_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY18_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY19_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY20_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'ORR_z'
base: ['PA1.FY17_uzy', '#base-z']

---
name: 'FY17_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY18_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY19_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'FY20_y'
base: ['PA1.FY17_uzy', '#base-y']

---
name: 'ORR_y'
base: ['PA1.FY17_uzy', '#base-y']
