# Specifications for validate_drp metrics against validation_data_decam

---
# Select the DECAM test dataset
id: 'base'
metadata_query:
  instrument: 'DECAM'
  dataset_repo_url: 'https://github.com/lsst/validation_data_decam.git'
  # May need to add specific visits and ccds for the test dataset

---
id: 'base-g'
base: '#base'
metadata_query:
  filter_name: 'g'

---
id: 'base-r'
base: '#base'
metadata_query:
  filter_name: 'r'

---
id: 'base-i'
base: '#base'
metadata_query:
  filter_name: 'i'

---
name: 'FY17_decam_g'
base: ['PA1.FY17_gri', '#base-g']

---
name: 'FY18_decam_g'
base: ['PA1.FY17_gri', '#base-g']

---
name: 'FY19_decam_g'
base: ['PA1.FY17_gri', '#base-g']

---
name: 'FY20_decam_g'
base: ['PA1.FY17_gri', '#base-g']

---
name: 'ORR_decam_g'
base: ['PA1.FY17_gri', '#base-g']

---
name: 'FY17_decam_r'
base: ['PA1.FY17_gri', '#base-r']

---
name: 'FY18_decam_r'
base: ['PA1.FY17_gri', '#base-r']

---
name: 'FY19_decam_r'
base: ['PA1.FY17_gri', '#base-r']

---
name: 'FY20_decam_r'
base: ['PA1.FY17_gri', '#base-r']

---
name: 'ORR_decam_r'
base: ['PA1.FY17_gri', '#base-r']

---
name: 'FY17_decam_i'
base: ['PA1.FY17_gri', '#base-i']

---
name: 'FY18_decam_i'
base: ['PA1.FY17_gri', '#base-i']

---
name: 'FY19_decam_i'
base: ['PA1.FY17_gri', '#base-i']

---
name: 'FY20_decam_i'
base: ['PA1.FY17_gri', '#base-i']

---
name: 'ORR_decam_i'
base: ['PA1.FY17_gri', '#base-i']
